---
- TemplateId: AddElementalResistance
  Id: AddElementalResistance
  AllowedItemTypes: 
   - Chest
   - Helmet
   - Legs

- TemplateId: AddElementalResistance
  Id: AddElementalResistanceRings
  AllowedItemTypes: 
   - Utility
  AllowedItemNames:
   - Gold Ruby Ring
   - Silver Ring

- TemplateId: AddElementalResistance
  Id: AddElementalResistanceBelts
  AllowedItemTypes: 
   - Utility
  AllowedItemNames:
  - Leather Belt
  - Aescfell Belt
  - Stánbrysan Belt
  - Eorðtilia Belt
  - Stulor Belt
  - Casul Belt
