---
- TemplateId: FrostResistance
  Id: AddFrostResistanceChest
  AllowedItemTypes: 
   - Chest
   - Helmet
   - Legs

- TemplateId: FrostResistance
  Id: AddFrostResistanceRings
  AllowedItemTypes: 
   - Utility
  AllowedItemNames:
   - Gold Ruby Ring
   - Silver Ring

- TemplateId: FrostResistance
  Id: AddFrostResistanceBelt
  AllowedItemTypes: 
   - Utility
  AllowedItemNames:
  - Leather Belt
  - Aescfell Belt
  - Stánbrysan Belt
  - Eorðtilia Belt
  - Stulor Belt
  - Casul Belt
