---
- TemplateId: LightningResistance
  Id: AddLightningResistance
  AllowedItemTypes: 
   - Chest
   - Helmet
   - Legs

- TemplateId: LightningResistance
  Id: AddLightningResistanceRings
  AllowedItemTypes: 
   - Utility
  AllowedItemNames:
   - Gold Ruby Ring
   - Silver Ring

- TemplateId: LightningResistance
  Id: AddLightningResistanceBelt
  AllowedItemTypes: 
   - Utility
  AllowedItemNames:
  - Leather Belt
  - Aescfell Belt
  - Stánbrysan Belt
  - Eorðtilia Belt
  - Stulor Belt
  - Casul Belt
