---
- TemplateId: SpiritResistance
  Id: AddSpiritResistance
  AllowedItemTypes: 
   - Chest
   - Helmet
   - Legs

- TemplateId: SpiritResistance
  Id: SpiritResistance
  AllowedItemTypes: 
   - Utility
  AllowedItemNames:
   - Gold Ruby Ring
   - Silver Ring

- TemplateId: SpiritResistance
  Id: AddSpiritResistanceBelt
  AllowedItemTypes: 
   - Utility
  AllowedItemNames:
  - Leather Belt
  - Aescfell Belt
  - Stánbrysan Belt
  - Eorðtilia Belt
  - Stulor Belt
  - Casul Belt
