---
- TemplateId: IncreaseStamina
  Id: IncreaseStaminaChest
  AllowedItemTypes: 
   - "Chest"

- TemplateId: IncreaseStamina
  Id: IncreaseStaminaHelmet
  AllowedItemTypes: 
   - "Helmet"

- TemplateId: IncreaseStamina
  Id: IncreaseStaminaLegs
  AllowedItemTypes: 
   - "Legs"
  ValuesPerRarity:
    Magic: {MinValue: 5, MaxValue: 10, Increment: 1}
    Rare: {MinValue: 10, MaxValue: 15, Increment: 1}
    Epic: {MinValue: 15, MaxValue: 20, Increment: 1}
    Legendary: {MinValue: 20, MaxValue: 25, Increment: 1}

- TemplateId: IncreaseStamina
  Id: IncreaseStaminaRings
  AllowedItemTypes: 
   - "Utility"
  AllowedItemNames:
   - "Gold Ruby Ring"
   - "Silver Ring"
  ValuesPerRarity:
    Magic: {MinValue: 5, MaxValue: 10, Increment: 1}
    Rare: {MinValue: 10, MaxValue: 15, Increment: 1}
    Epic: {MinValue: 15, MaxValue: 20, Increment: 1}
    Legendary: {MinValue: 20, MaxValue: 25, Increment: 1}

- TemplateId: IncreaseStamina
  Id: IncreaseStaminaBelt
  AllowedItemTypes: 
   - "Utility"
  AllowedItemNames:
   - "Leather Belt"
  ValuesPerRarity:
    Magic: {MinValue: 5, MaxValue: 10, Increment: 1}
    Rare: {MinValue: 10, MaxValue: 15, Increment: 1}
    Epic: {MinValue: 15, MaxValue: 20, Increment: 1}
    Legendary: {MinValue: 20, MaxValue: 25, Increment: 1}