---
# AddPhysicalDamages
- TemplateId: AddBluntDamage
  ParentTemplateIds:
  - ExcludeAddElementalDamageEffects
  Type: AddBluntDamage
  DisplayText: $mod_epicloot_me_addbluntdamage_display
  Description: $mod_epicloot_me_addbluntdamage_desc
  ExclusiveEffectTypes:
  - AddSlashingDamage
  - AddPiercingDamage
  Prefixes:
  - $mod_epicloot_me_addbluntdamage_prefix1
  Suffixes:
  - $mod_epicloot_me_addbluntdamage_suffix1


- TemplateId: AddSlashingDamage
  ParentTemplateIds:
  - ExcludeAddElementalDamageEffects
  Type: AddSlashingDamage
  DisplayText: $mod_epicloot_me_addslashingdamage_display
  Description: $mod_epicloot_me_addslashingdamage_desc
  ExclusiveEffectTypes:
  - AddBluntDamage
  - AddPiercingDamage
  Prefixes:
  - $mod_epicloot_me_addslashingdamage_prefix1
  Suffixes:
  - $mod_epicloot_me_addslashingdamage_suffix1


- TemplateId: AddPiercingDamage
  ParentTemplateIds:
  - ExcludeAddElementalDamageEffects
  Type: AddPiercingDamage
  DisplayText: $mod_epicloot_me_addpiercingdamage_display
  Description: $mod_epicloot_me_addpiercingdamage_desc
  ExclusiveEffectTypes:
  - AddSlashingDamage
  - AddBluntDamage
  Prefixes:
  - $mod_epicloot_me_addpiercingdamage_prefix1
  Suffixes:
  - $mod_epicloot_me_addpiercingdamage_suffix1


# ExlusionRule
- TemplateId: ExcludeAddPhysicalDamageEffects
  ExclusiveEffectTypes:
  - AddSlashingDamage
  - AddBluntDamage
  - AddPiercingDamage


# ByClass
- TemplateId: AddPhysicalDamageOneHandedFast
  AllowedItemTypes: 
  - OneHandedWeapon
  AllowedSkillTypes:
  - Knives
  - Spears
  - Unarmed
  ValuesPerRarity:
    Magic: {MinValue: 1, MaxValue: 2, Increment: 1}
    Rare: {MinValue: 2, MaxValue: 3, Increment: 1}
    Epic: {MinValue: 3, MaxValue: 5, Increment: 1}
    Legendary: {MinValue: 5, MaxValue: 7, Increment: 1}



- TemplateId: AddPhysicalDamageOneHandedSlow
  AllowedItemTypes: 
  - OneHandedWeapon
  - Torch
  AllowedSkillTypes:
  - Clubs
  - Swords
  - Axes
  ValuesPerRarity:
    Magic: {MinValue: 2, MaxValue: 3, Increment: 1}
    Rare: {MinValue: 3, MaxValue: 5, Increment: 1}
    Epic: {MinValue: 5, MaxValue: 8, Increment: 1}
    Legendary: {MinValue: 8, MaxValue: 12, Increment: 1}



- TemplateId: AddPhysicalDamageTwoHanded
  AllowedItemTypes: 
  - TwoHandedWeapon
  ValuesPerRarity:
    Magic: {MinValue: 3, MaxValue: 4, Increment: 1}
    Rare: {MinValue: 4, MaxValue: 7, Increment: 1}
    Epic: {MinValue: 7, MaxValue: 10, Increment: 1}
    Legendary: {MinValue: 10, MaxValue: 15, Increment: 1}



- TemplateId: AddPhysicalDamageBows
  AllowedItemTypes: 
  - Bow
  ValuesPerRarity:
    Magic: {MinValue: 1, MaxValue: 2, Increment: 1}
    Rare: {MinValue: 2, MaxValue: 3, Increment: 1}
    Epic: {MinValue: 4, MaxValue: 7, Increment: 1}
    Legendary: {MinValue: 7, MaxValue: 10, Increment: 1}


# Mixins - Blunt
- TemplateId: AddBluntDamageOneHandedFast
  ParentTemplateIds:
  - AddBluntDamage
  - AddPhysicalDamageOneHandedFast



- TemplateId: AddBluntDamageOneHandedSlow
  ParentTemplateIds:
  - AddBluntDamage
  - AddPhysicalDamageOneHandedSlow



- TemplateId: AddBluntDamageTwoHanded
  ParentTemplateIds:
  - AddBluntDamage
  - AddPhysicalDamageTwoHanded



- TemplateId: AddBluntDamageBows
  ParentTemplateIds:
  - AddBluntDamage
  - AddPhysicalDamageBows


# Mixins - Slashing
- TemplateId: AddSlashingDamageOneHandedFast
  ParentTemplateIds:
  - AddSlashingDamage
  - AddPhysicalDamageOneHandedFast



- TemplateId: AddSlashingDamageOneHandedSlow
  ParentTemplateIds:
  - AddSlashingDamage
  - AddPhysicalDamageOneHandedSlow



- TemplateId: AddSlashingDamageTwoHanded
  ParentTemplateIds:
  - AddSlashingDamage
  - AddPhysicalDamageTwoHanded



- TemplateId: AddSlashingDamageBows
  ParentTemplateIds:
  - AddSlashingDamage
  - AddPhysicalDamageBows



# Mixins - Piercing
- TemplateId: AddPiercingDamageOneHandedFast
  ParentTemplateIds:
  - AddPiercingDamage
  - AddPhysicalDamageOneHandedFast



- TemplateId: AddPiercingDamageOneHandedSlow
  ParentTemplateIds:
  - AddPiercingDamage
  - AddPhysicalDamageOneHandedSlow



- TemplateId: AddPiercingDamageTwoHanded
  ParentTemplateIds:
  - AddPiercingDamage
  - AddPhysicalDamageTwoHanded



- TemplateId: AddPiercingDamageBows
  ParentTemplateIds:
  - AddPiercingDamage
  - AddPhysicalDamageBows



# ModifyPhysicalDamage
- TemplateId: ModifyPhysicalDamage
  Type: ModifyPhysicalDamage
  ParentTemplateIds:
  - ExcludeAddPhysicalDamageEffects
  DisplayText: $mod_epicloot_me_modifyphysicaldamage_display
  Description: $mod_epicloot_me_modifyphysicaldamage_desc
  ItemHasPhysicalDamage: true
  AllowedItemTypes: 
  - OneHandedWeapon
  - TwoHandedWeapon
  - Bow
  ValuesPerRarity:
    Magic: {MinValue: 10, MaxValue: 10, Increment: 5}
    Rare: {MinValue: 10, MaxValue: 15, Increment: 5}
    Epic: {MinValue: 15, MaxValue: 15, Increment: 5}
    Legendary: {MinValue: 15, MaxValue: 20, Increment: 5}
  Prefixes:
  - $mod_epicloot_me_modifyphysicaldamage_prefix1
  - $mod_epicloot_me_modifyphysicaldamage_prefix2
  - $mod_epicloot_me_modifyphysicaldamage_prefix3
  - $mod_epicloot_me_modifyphysicaldamage_prefix4
  - $mod_epicloot_me_modifyphysicaldamage_prefix5
  - $mod_epicloot_me_modifyphysicaldamage_prefix6
  - $mod_epicloot_me_modifyphysicaldamage_prefix7
  - $mod_epicloot_me_modifyphysicaldamage_prefix8
  Suffixes:
  - $mod_epicloot_me_modifyphysicaldamage_suffix1
  - $mod_epicloot_me_modifyphysicaldamage_suffix2
  - $mod_epicloot_me_modifyphysicaldamage_suffix3
  - $mod_epicloot_me_modifyphysicaldamage_suffix4
  - $mod_epicloot_me_modifyphysicaldamage_suffix5