---
- TemplateId: SlashingResistance
  Id: SlashingResistance
  AllowedItemTypes: 
   - Chest
   - Helmet
   - Legs

- TemplateId: SlashingResistance
  Id: AddSlashingResistanceRings
  AllowedItemTypes: 
   - Utility
  AllowedItemNames:
   - Gold Ruby Ring
   - Silver Ring

- TemplateId: SlashingResistance
  Id: AddSlashingResistanceBelt
  AllowedItemTypes: 
   - Utility
  AllowedItemNames:
  - Leather Belt
  - Aescfell Belt
  - Stánbrysan Belt
  - Eorðtilia Belt
  - Stulor Belt
  - Casul Belt
