---
- TemplateId: IncreaseVitals

- TemplateId: IncreaseHealth
  ParentTemplateIds:
  - IncreaseVitals
  Type: IncreaseHealth

- TemplateId: IncreaseHealthStrong
  ParentTemplateIds:
  - IncreaseHealth
  ValuesPerRarity:
    Magic: {MinValue: 10, MaxValue: 15, Increment: 1}
    Rare: {MinValue: 15, MaxValue: 20, Increment: 1}
    Epic: {MinValue: 20, MaxValue: 25, Increment: 1}
    Legendary: {MinValue: 25, MaxValue: 30, Increment: 1}

- TemplateId: IncreaseHealthWeak
  ParentTemplateIds:
  - IncreaseHealth
  ValuesPerRarity:
    Magic: {MinValue: 5, MaxValue: 10, Increment: 1}
    Rare: {MinValue: 10, MaxValue: 15, Increment: 1}
    Epic: {MinValue: 15, MaxValue: 20, Increment: 1}
    Legendary: {MinValue: 20, MaxValue: 25, Increment: 1}

- TemplateId: IncreaseStamina
  ParentTemplateIds:
  - IncreaseVitals
  Type: IncreaseStamina
