---
- TemplateId: AddPiercingDamageOneHandedFast
  Id: AddPiercingDamageOneHandedFast

- TemplateId: AddPiercingDamageOneHandedSlow
  Id: AddPiercingDamageOneHandedSlow

- TemplateId: AddPiercingDamageTwoHanded
  Id: AddPiercingDamageTwoHanded

- TemplateId: AddPiercingDamageBows
  Id: AddPiercingDamageBows
