---
- TemplateId: AddFrostDamageOneHandedFast
  Id: AddFrostDamageOneHandedFast

- TemplateId: AddFrostDamageOneHandedSlow
  Id: AddFrostDamageOneHandedSlow

- TemplateId: AddFrostDamageTwoHanded
  Id: AddFrostDamageTwoHanded

- TemplateId: AddFrostDamageBows
  Id: AddFrostDamageBows
