---
- TemplateId: AddSpiritDamageOneHandedFast
  Id: AddSpiritDamageOneHandedFast

- TemplateId: AddSpiritDamageOneHandedSlow
  Id: AddSpiritDamageOneHandedSlow

- TemplateId: AddSpiritDamageTwoHanded
  Id: AddSpiritDamageTwoHanded

- TemplateId: AddSpiritDamageBows
  Id: AddSpiritDamageBows

